// PRESSURE - Zen Mode Levels
// Additional levels for Zen mode - pure puzzle, no pressure.
// Generated using the engine's level generator for guaranteed solvability.

import { Level } from '../../types';
import { generateLevel } from '../../levels';

// Generate levels at module load time with retry logic
function createZenLevels(): Level[] {
  const levels: Level[] = [];

  // World 4: Flow - 5x5 grids, 2 nodes, easy
  const world4Names = ['Stream', 'Ripple', 'Current', 'Wave'];
  for (let i = 0; i < 4; i++) {
    const generated = generateLevel({
      gridSize: 5,
      nodeCount: 2,
      difficulty: 'easy',
      decoys: false,
    });
    if (generated) {
      levels.push({
        ...generated,
        id: 101 + i,
        name: world4Names[i],
        world: 4,
        compressionDelay: 999999,
      });
    }
  }

  // World 5: Peace - 6x6 grids, 2 nodes (simpler, more reliable)
  const world5Names = ['Calm', 'Serenity', 'Tranquil'];
  for (let i = 0; i < 3; i++) {
    const generated = generateLevel({
      gridSize: 6,
      nodeCount: 2,
      difficulty: 'medium',
      decoys: true,
    });
    if (generated) {
      levels.push({
        ...generated,
        id: 105 + i,
        name: world5Names[i],
        world: 5,
        compressionDelay: 999999,
      });
    }
  }

  // World 6: Nirvana - 7x7 grids, 3 nodes, hard
  const world6Names = ['Enlightenment', 'Bliss', 'Nirvana'];
  for (let i = 0; i < 3; i++) {
    const generated = generateLevel({
      gridSize: 7,
      nodeCount: 3,
      difficulty: 'hard',
      decoys: true,
    });
    if (generated) {
      levels.push({
        ...generated,
        id: 108 + i,
        name: world6Names[i],
        world: 6,
        compressionDelay: 999999,
      });
    }
  }

  return levels;
}

// Custom "Stream (edited)" level with pre-computed scrambled rotations
export const STREAM_EDITED_LEVEL: Level = {
  id: 200,
  name: 'Stream (edited)',
  world: 4,
  gridSize: 10,
  maxMoves: 24,
  compressionDelay: 999999,
  goalNodes: [
    { x: 2, y: 2 },
    { x: 1, y: 1 },
    { x: 5, y: 5 },
    { x: 1, y: 2 },
    { x: 8, y: 1 },
    { x: 8, y: 7 },
    { x: 1, y: 8 },
    { x: 4, y: 6 },
  ],
  tiles: [
    // Walls
    {
      id: 'wall-0-0',
      type: 'wall',
      x: 0,
      y: 0,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-4',
      type: 'wall',
      x: 0,
      y: 4,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-1-0',
      type: 'wall',
      x: 1,
      y: 0,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-1-4',
      type: 'wall',
      x: 1,
      y: 4,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-1',
      type: 'wall',
      x: 0,
      y: 1,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-4-1',
      type: 'wall',
      x: 4,
      y: 1,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-2-0',
      type: 'wall',
      x: 2,
      y: 0,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-2-4',
      type: 'wall',
      x: 2,
      y: 4,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-2',
      type: 'wall',
      x: 0,
      y: 2,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-4-2',
      type: 'wall',
      x: 4,
      y: 2,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-3-0',
      type: 'wall',
      x: 3,
      y: 0,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-3',
      type: 'wall',
      x: 0,
      y: 3,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-4-3',
      type: 'wall',
      x: 4,
      y: 3,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-4-0',
      type: 'wall',
      x: 4,
      y: 0,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-5-7',
      type: 'wall',
      x: 5,
      y: 7,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-3-6',
      type: 'wall',
      x: 3,
      y: 6,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-2-6',
      type: 'wall',
      x: 2,
      y: 6,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-1-6',
      type: 'wall',
      x: 1,
      y: 6,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-6',
      type: 'wall',
      x: 0,
      y: 6,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-6-8',
      type: 'wall',
      x: 6,
      y: 8,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-5-8',
      type: 'wall',
      x: 5,
      y: 8,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-5-9',
      type: 'wall',
      x: 5,
      y: 9,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-6-9',
      type: 'wall',
      x: 6,
      y: 9,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-6-3',
      type: 'wall',
      x: 6,
      y: 3,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-6-2',
      type: 'wall',
      x: 6,
      y: 2,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-6-0',
      type: 'wall',
      x: 6,
      y: 0,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-7-3',
      type: 'wall',
      x: 7,
      y: 3,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-8-3',
      type: 'wall',
      x: 8,
      y: 3,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-3',
      type: 'wall',
      x: 9,
      y: 3,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-6',
      type: 'wall',
      x: 9,
      y: 6,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-7-5',
      type: 'wall',
      x: 7,
      y: 5,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-9',
      type: 'wall',
      x: 9,
      y: 9,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-8',
      type: 'wall',
      x: 9,
      y: 8,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-7',
      type: 'wall',
      x: 9,
      y: 7,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-5',
      type: 'wall',
      x: 9,
      y: 5,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-4',
      type: 'wall',
      x: 9,
      y: 4,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-2',
      type: 'wall',
      x: 9,
      y: 2,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-0',
      type: 'wall',
      x: 9,
      y: 0,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-9-1',
      type: 'wall',
      x: 9,
      y: 1,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-7',
      type: 'wall',
      x: 0,
      y: 7,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-8',
      type: 'wall',
      x: 0,
      y: 8,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-0-9',
      type: 'wall',
      x: 0,
      y: 9,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    {
      id: 'wall-8-5',
      type: 'wall',
      x: 8,
      y: 5,
      connections: [],
      isGoalNode: false,
      canRotate: false,
    },
    // Nodes
    {
      id: 'node-2-2',
      type: 'node',
      x: 2,
      y: 2,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'node-1-1',
      type: 'node',
      x: 1,
      y: 1,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'node-5-5',
      type: 'node',
      x: 5,
      y: 5,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'node-8-1',
      type: 'node',
      x: 8,
      y: 1,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'node-8-7',
      type: 'node',
      x: 8,
      y: 7,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'node-1-8',
      type: 'node',
      x: 1,
      y: 8,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    // Paths with scrambled rotations (deterministic)
    {
      id: 'path-4-7',
      type: 'path',
      x: 4,
      y: 7,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-4-6',
      type: 'path',
      x: 4,
      y: 6,
      connections: ['up', 'left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-6-1',
      type: 'path',
      x: 6,
      y: 1,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-3-3',
      type: 'path',
      x: 3,
      y: 3,
      connections: ['right', 'up'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-2-3',
      type: 'path',
      x: 2,
      y: 3,
      connections: ['down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-3-4',
      type: 'path',
      x: 3,
      y: 4,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-3-5',
      type: 'path',
      x: 3,
      y: 5,
      connections: ['down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-4-5',
      type: 'path',
      x: 4,
      y: 5,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-5-4',
      type: 'path',
      x: 5,
      y: 4,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-5-3',
      type: 'path',
      x: 5,
      y: 3,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-5-2',
      type: 'path',
      x: 5,
      y: 2,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-5-1',
      type: 'path',
      x: 5,
      y: 1,
      connections: ['left', 'up'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-7-1',
      type: 'path',
      x: 7,
      y: 1,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-5-6',
      type: 'path',
      x: 5,
      y: 6,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-4-8',
      type: 'path',
      x: 4,
      y: 8,
      connections: ['down', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-3-8',
      type: 'path',
      x: 3,
      y: 8,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-2-8',
      type: 'path',
      x: 2,
      y: 8,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-6-7',
      type: 'path',
      x: 6,
      y: 7,
      connections: ['down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-7-7',
      type: 'path',
      x: 7,
      y: 7,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-6-6',
      type: 'path',
      x: 6,
      y: 6,
      connections: ['right', 'up'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'path-1-2',
      type: 'path',
      x: 1,
      y: 2,
      connections: ['down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
  ],
};

export const ZEN_LEVELS_SET_2: Level[] = createZenLevels();
