// PRESSURE - Zen Mode Levels
// Additional levels for Zen mode - pure puzzle, no pressure.
// Generated using the engine's level generator for guaranteed solvability.

import { Level } from '../../types';
import { generateLevel } from '../../levels';

// Generate levels at module load time with retry logic
function createZenLevels(): Level[] {
  const levels: Level[] = [];

  // World 4: Flow - 5x5 grids, 2 nodes, easy
  const world4Names = ['Stream', 'Ripple', 'Current', 'Wave'];
  for (let i = 0; i < 4; i++) {
    const generated = generateLevel({
      gridSize: 5,
      nodeCount: 2,
      difficulty: 'easy',
      decoys: false,
    });
    if (generated) {
      levels.push({
        ...generated,
        id: 101 + i,
        name: world4Names[i],
        world: 4,
        compressionDelay: 999999,
      });
    }
  }

  // World 5: Peace - 6x6 grids, 2 nodes (simpler, more reliable)
  const world5Names = ['Calm', 'Serenity', 'Tranquil'];
  for (let i = 0; i < 3; i++) {
    const generated = generateLevel({
      gridSize: 6,
      nodeCount: 2,
      difficulty: 'medium',
      decoys: true,
    });
    if (generated) {
      levels.push({
        ...generated,
        id: 105 + i,
        name: world5Names[i],
        world: 5,
        compressionDelay: 999999,
      });
    }
  }

  // World 6: Nirvana - 7x7 grids, 3 nodes, hard
  const world6Names = ['Enlightenment', 'Bliss', 'Nirvana'];
  for (let i = 0; i < 3; i++) {
    const generated = generateLevel({
      gridSize: 7,
      nodeCount: 3,
      difficulty: 'hard',
      decoys: true,
    });
    if (generated) {
      levels.push({
        ...generated,
        id: 108 + i,
        name: world6Names[i],
        world: 6,
        compressionDelay: 999999,
      });
    }
  }

  return levels;
}

// NEXUS PRIME - 10x10 grid with 5 goal nodes
// Scrambled: 5 tiles need rotation to solve
export const RIPPLE_EDITED_LEVEL: Level = {
  id: 201,
  name: 'Nexus Prime',
  world: 4,
  gridSize: 10,
  maxMoves: 5,
  compressionDelay: 999999,
  goalNodes: [
    { x: 2, y: 1 },
    { x: 3, y: 2 },
    { x: 4, y: 5 },
    { x: 4, y: 9 },
    { x: 7, y: 8 },
  ],
  tiles: [
    // Walls - top left section
    { id: 'w-0-0', type: 'wall', x: 0, y: 0, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-4', type: 'wall', x: 0, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-1-0', type: 'wall', x: 1, y: 0, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-1-4', type: 'wall', x: 1, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-1', type: 'wall', x: 0, y: 1, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-1', type: 'wall', x: 4, y: 1, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-2-0', type: 'wall', x: 2, y: 0, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-2-4', type: 'wall', x: 2, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-2', type: 'wall', x: 0, y: 2, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-2', type: 'wall', x: 4, y: 2, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-3-0', type: 'wall', x: 3, y: 0, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-3-4', type: 'wall', x: 3, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-3', type: 'wall', x: 0, y: 3, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-0', type: 'wall', x: 4, y: 0, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-4', type: 'wall', x: 4, y: 4, connections: [], isGoalNode: false, canRotate: false },
    // Walls - right section
    { id: 'w-5-2', type: 'wall', x: 5, y: 2, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-1', type: 'wall', x: 5, y: 1, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-0', type: 'wall', x: 5, y: 0, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-4', type: 'wall', x: 5, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-6-4', type: 'wall', x: 6, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-7-4', type: 'wall', x: 7, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-8-3', type: 'wall', x: 8, y: 3, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-8-4', type: 'wall', x: 8, y: 4, connections: [], isGoalNode: false, canRotate: false },
    // Walls - bottom section
    { id: 'w-9-6', type: 'wall', x: 9, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-8-6', type: 'wall', x: 8, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-7-6', type: 'wall', x: 7, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-6', type: 'wall', x: 5, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-7', type: 'wall', x: 5, y: 7, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-8', type: 'wall', x: 5, y: 8, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-7', type: 'wall', x: 4, y: 7, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-3-7', type: 'wall', x: 3, y: 7, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-2-7', type: 'wall', x: 2, y: 7, connections: [], isGoalNode: false, canRotate: false },
    // Goal nodes
    {
      id: 'n-2-1',
      type: 'node',
      x: 2,
      y: 1,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-3-2',
      type: 'node',
      x: 3,
      y: 2,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-4-5',
      type: 'node',
      x: 4,
      y: 5,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-4-9',
      type: 'node',
      x: 4,
      y: 9,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-7-8',
      type: 'node',
      x: 7,
      y: 8,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    // Paths - top section (some scrambled)
    {
      id: 'p-3-1',
      type: 'path',
      x: 3,
      y: 1,
      connections: ['up', 'right'],  // SCRAMBLED: was ['down', 'left']
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-3',
      type: 'path',
      x: 3,
      y: 3,
      connections: ['up', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-4-3',
      type: 'path',
      x: 4,
      y: 3,
      connections: ['up', 'down'],  // SCRAMBLED: was ['left', 'right']
      isGoalNode: false,
      canRotate: true,
    },
    // Paths - middle section
    {
      id: 'p-5-3',
      type: 'path',
      x: 5,
      y: 3,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-3',
      type: 'path',
      x: 6,
      y: 3,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-3',
      type: 'path',
      x: 7,
      y: 3,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-2',
      type: 'path',
      x: 7,
      y: 2,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-2',
      type: 'path',
      x: 6,
      y: 2,
      connections: ['down', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-2',
      type: 'path',
      x: 8,
      y: 2,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-2',
      type: 'path',
      x: 9,
      y: 2,
      connections: ['up', 'down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-3',
      type: 'path',
      x: 9,
      y: 3,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-4',
      type: 'path',
      x: 9,
      y: 4,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-5',
      type: 'path',
      x: 9,
      y: 5,
      connections: ['up', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-5',
      type: 'path',
      x: 7,
      y: 5,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-5-5',
      type: 'path',
      x: 5,
      y: 5,
      connections: ['up', 'down'],  // SCRAMBLED: was ['left', 'right']
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-5',
      type: 'path',
      x: 6,
      y: 5,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-5',
      type: 'path',
      x: 8,
      y: 5,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    // Paths - bottom section
    {
      id: 'p-4-6',
      type: 'path',
      x: 4,
      y: 6,
      connections: ['up', 'left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-6',
      type: 'path',
      x: 3,
      y: 6,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-6',
      type: 'path',
      x: 2,
      y: 6,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-5',
      type: 'path',
      x: 2,
      y: 5,
      connections: ['down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-5',
      type: 'path',
      x: 1,
      y: 5,
      connections: ['down', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-6',
      type: 'path',
      x: 1,
      y: 6,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-7',
      type: 'path',
      x: 1,
      y: 7,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-8',
      type: 'path',
      x: 1,
      y: 8,
      connections: ['up', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-8',
      type: 'path',
      x: 2,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-8',
      type: 'path',
      x: 3,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-4-8',
      type: 'path',
      x: 4,
      y: 8,
      connections: ['up', 'down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-6',
      type: 'path',
      x: 6,
      y: 6,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-7',
      type: 'path',
      x: 6,
      y: 7,
      connections: ['right', 'down', 'up'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-8',
      type: 'path',
      x: 6,
      y: 8,
      connections: ['up', 'down', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-7',
      type: 'path',
      x: 7,
      y: 7,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-7',
      type: 'path',
      x: 8,
      y: 7,
      connections: ['down', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-8',
      type: 'path',
      x: 8,
      y: 8,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-5-9',
      type: 'path',
      x: 5,
      y: 9,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-9',
      type: 'path',
      x: 6,
      y: 9,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-9',
      type: 'path',
      x: 7,
      y: 9,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-9',
      type: 'path',
      x: 8,
      y: 9,
      connections: ['up', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
  ],
};

// VORTEX - 10x10 grid with 5 goal nodes
// Scrambled: 7 tiles need rotation to solve
export const STREAM_EDITED_LEVEL: Level = {
  id: 200,
  name: 'Vortex',
  world: 4,
  gridSize: 10,
  maxMoves: 7,
  compressionDelay: 999999,
  goalNodes: [
    { x: 1, y: 8 },
    { x: 8, y: 3 },
    { x: 5, y: 4 },
    { x: 5, y: 2 },
    { x: 2, y: 2 },
  ],
  tiles: [
    // Walls - left side
    { id: 'w-0-1', type: 'wall', x: 0, y: 1, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-1-1', type: 'wall', x: 1, y: 1, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-1', type: 'wall', x: 5, y: 1, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-6-1', type: 'wall', x: 6, y: 1, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-6-2', type: 'wall', x: 6, y: 2, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-6-3', type: 'wall', x: 6, y: 3, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-6-4', type: 'wall', x: 6, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-7-4', type: 'wall', x: 7, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-7-2', type: 'wall', x: 7, y: 2, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-8-2', type: 'wall', x: 8, y: 2, connections: [], isGoalNode: false, canRotate: false },
    // Walls - right side
    { id: 'w-6-6', type: 'wall', x: 6, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-8-6', type: 'wall', x: 8, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-8-7', type: 'wall', x: 8, y: 7, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-6-9', type: 'wall', x: 6, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-7-9', type: 'wall', x: 7, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-8-9', type: 'wall', x: 8, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-9-9', type: 'wall', x: 9, y: 9, connections: [], isGoalNode: false, canRotate: false },
    // Walls - center
    { id: 'w-3-9', type: 'wall', x: 3, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-3-7', type: 'wall', x: 3, y: 7, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-3-6', type: 'wall', x: 3, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-3-4', type: 'wall', x: 3, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-3-5', type: 'wall', x: 3, y: 5, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-3', type: 'wall', x: 4, y: 3, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-3', type: 'wall', x: 5, y: 3, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-7', type: 'wall', x: 5, y: 7, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-6', type: 'wall', x: 5, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-6', type: 'wall', x: 4, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-5', type: 'wall', x: 4, y: 5, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-4', type: 'wall', x: 4, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-1-3', type: 'wall', x: 1, y: 3, connections: [], isGoalNode: false, canRotate: false },
    // Walls - edges
    { id: 'w-0-2', type: 'wall', x: 0, y: 2, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-3', type: 'wall', x: 0, y: 3, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-0', type: 'wall', x: 0, y: 0, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-4', type: 'wall', x: 0, y: 4, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-5', type: 'wall', x: 0, y: 5, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-6', type: 'wall', x: 0, y: 6, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-7', type: 'wall', x: 0, y: 7, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-8', type: 'wall', x: 0, y: 8, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-0-9', type: 'wall', x: 0, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-1-9', type: 'wall', x: 1, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-2-9', type: 'wall', x: 2, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-4-9', type: 'wall', x: 4, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-5-9', type: 'wall', x: 5, y: 9, connections: [], isGoalNode: false, canRotate: false },
    { id: 'w-7-3', type: 'wall', x: 7, y: 3, connections: [], isGoalNode: false, canRotate: false },
    // Goal nodes
    {
      id: 'n-1-8',
      type: 'node',
      x: 1,
      y: 8,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-8-3',
      type: 'node',
      x: 8,
      y: 3,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-5-4',
      type: 'node',
      x: 5,
      y: 4,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-5-2',
      type: 'node',
      x: 5,
      y: 2,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    {
      id: 'n-2-2',
      type: 'node',
      x: 2,
      y: 2,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: true,
      canRotate: false,
    },
    // Paths - top row
    {
      id: 'p-2-1',
      type: 'path',
      x: 2,
      y: 1,
      connections: ['down', 'right'],  // SCRAMBLED: was ['up', 'down', 'left']
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-1',
      type: 'path',
      x: 3,
      y: 1,
      connections: ['up', 'down'],  // SCRAMBLED: was ['left', 'right']
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-4-1',
      type: 'path',
      x: 4,
      y: 1,
      connections: ['down', 'left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-1',
      type: 'path',
      x: 7,
      y: 1,
      connections: ['up', 'down'],  // SCRAMBLED: was ['left', 'right']
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-1',
      type: 'path',
      x: 8,
      y: 1,
      connections: ['up', 'down', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    // Paths - row 0
    {
      id: 'p-4-0',
      type: 'path',
      x: 4,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-0',
      type: 'path',
      x: 2,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-0',
      type: 'path',
      x: 3,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-5-0',
      type: 'path',
      x: 5,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-0',
      type: 'path',
      x: 6,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-0',
      type: 'path',
      x: 7,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-0',
      type: 'path',
      x: 8,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-0',
      type: 'path',
      x: 9,
      y: 0,
      connections: ['left', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-1',
      type: 'path',
      x: 9,
      y: 1,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-2',
      type: 'path',
      x: 9,
      y: 2,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-3',
      type: 'path',
      x: 9,
      y: 3,
      connections: ['left', 'down', 'up'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-4',
      type: 'path',
      x: 9,
      y: 4,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-4',
      type: 'path',
      x: 8,
      y: 4,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-5',
      type: 'path',
      x: 8,
      y: 5,
      connections: ['left', 'up'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-5',
      type: 'path',
      x: 7,
      y: 5,
      connections: ['up', 'down', 'left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-5',
      type: 'path',
      x: 9,
      y: 5,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-6',
      type: 'path',
      x: 9,
      y: 6,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-7',
      type: 'path',
      x: 9,
      y: 7,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-9-8',
      type: 'path',
      x: 9,
      y: 8,
      connections: ['up', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-8-8',
      type: 'path',
      x: 8,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-8',
      type: 'path',
      x: 7,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-8',
      type: 'path',
      x: 6,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-5-8',
      type: 'path',
      x: 5,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-4-8',
      type: 'path',
      x: 4,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-8',
      type: 'path',
      x: 3,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-8',
      type: 'path',
      x: 2,
      y: 8,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    // Paths - middle section
    {
      id: 'p-5-5',
      type: 'path',
      x: 5,
      y: 5,
      connections: ['down', 'left'],  // SCRAMBLED: was ['up', 'right']
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-6-5',
      type: 'path',
      x: 6,
      y: 5,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-7',
      type: 'path',
      x: 1,
      y: 7,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-6',
      type: 'path',
      x: 1,
      y: 6,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-5',
      type: 'path',
      x: 1,
      y: 5,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-4',
      type: 'path',
      x: 1,
      y: 4,
      connections: ['right', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-0',
      type: 'path',
      x: 1,
      y: 0,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-1-2',
      type: 'path',
      x: 1,
      y: 2,
      connections: ['up', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-4',
      type: 'path',
      x: 2,
      y: 4,
      connections: ['up', 'left'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-3',
      type: 'path',
      x: 2,
      y: 3,
      connections: ['up', 'down'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-2',
      type: 'path',
      x: 3,
      y: 2,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-4-2',
      type: 'path',
      x: 4,
      y: 2,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-5',
      type: 'path',
      x: 2,
      y: 5,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-6',
      type: 'path',
      x: 2,
      y: 6,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-2-7',
      type: 'path',
      x: 2,
      y: 7,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-3-3',
      type: 'path',
      x: 3,
      y: 3,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-4-7',
      type: 'path',
      x: 4,
      y: 7,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-6',
      type: 'path',
      x: 7,
      y: 6,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
    {
      id: 'p-7-7',
      type: 'path',
      x: 7,
      y: 7,
      connections: ['left', 'right'],
      isGoalNode: false,
      canRotate: true,
    },
  ],
};

export const ZEN_LEVELS_SET_2: Level[] = createZenLevels();
