import { Level } from '../../types';

export const QUANTUM_CHAIN_LEVELS: Level[] = [
  {
    id: 201,
    name: 'Quantum Intro',
    world: 1,
    gridSize: 7,
    tiles: [
      // Row 0: 5 + 3 = 8 → Target
      {
        id: '0-0',
        x: 0,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '1-0',
        x: 1,
        y: 0,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '2-0',
        x: 2,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '3-0',
        x: 3,
        y: 0,
        type: 'target',
        connections: [],
        canRotate: false,
        isGoalNode: true,
        displayData: { targetSum: 8, isFulfilled: false },
      },
      {
        id: '4-0',
        x: 4,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '5-0',
        x: 5,
        y: 0,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '6-0',
        x: 6,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      // Row 1
      {
        id: '0-1',
        x: 0,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '1-1',
        x: 1,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '2-1',
        x: 2,
        y: 1,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '3-1',
        x: 3,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '4-1',
        x: 4,
        y: 1,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '5-1',
        x: 5,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '6-1',
        x: 6,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 9 },
      },
      // Row 2
      {
        id: '0-2',
        x: 0,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '1-2',
        x: 1,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '2-2',
        x: 2,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '3-2',
        x: 3,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '4-2',
        x: 4,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '5-2',
        x: 5,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '6-2',
        x: 6,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      // Row 3
      {
        id: '0-3',
        x: 0,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '1-3',
        x: 1,
        y: 3,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '2-3',
        x: 2,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 8 },
      },
      {
        id: '3-3',
        x: 3,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '4-3',
        x: 4,
        y: 3,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '5-3',
        x: 5,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '6-3',
        x: 6,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      // Row 4
      {
        id: '0-4',
        x: 0,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '1-4',
        x: 1,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '2-4',
        x: 2,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '3-4',
        x: 3,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 9 },
      },
      {
        id: '4-4',
        x: 4,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '5-4',
        x: 5,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '6-4',
        x: 6,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      // Row 5
      {
        id: '0-5',
        x: 0,
        y: 5,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '1-5',
        x: 1,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '2-5',
        x: 2,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '3-5',
        x: 3,
        y: 5,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '4-5',
        x: 4,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '5-5',
        x: 5,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 8 },
      },
      {
        id: '6-5',
        x: 6,
        y: 5,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      // Row 6
      {
        id: '0-6',
        x: 0,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '1-6',
        x: 1,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '2-6',
        x: 2,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '3-6',
        x: 3,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '4-6',
        x: 4,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '5-6',
        x: 5,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '6-6',
        x: 6,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 9 },
      },
    ],
    goalNodes: [{ x: 3, y: 0 }],
    maxMoves: 99,
    compressionDelay: 0,
    compressionEnabled: false,
    targetScore: 0,
    timeLimit: 0,
  },
  {
    id: 202,
    name: 'Flux Challenge',
    world: 1,
    gridSize: 7,
    tiles: [
      // Row 0 - with quantum flux
      {
        id: '0-0',
        x: 0,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '1-0',
        x: 1,
        y: 0,
        type: 'quantumFlux',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { effect: 'double' },
      },
      {
        id: '2-0',
        x: 2,
        y: 0,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '3-0',
        x: 3,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '4-0',
        x: 4,
        y: 0,
        type: 'target',
        connections: [],
        canRotate: false,
        isGoalNode: true,
        displayData: { targetSum: 8, isFulfilled: false },
      },
      {
        id: '5-0',
        x: 5,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '6-0',
        x: 6,
        y: 0,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      // Row 1
      {
        id: '0-1',
        x: 0,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '1-1',
        x: 1,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '2-1',
        x: 2,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '3-1',
        x: 3,
        y: 1,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '4-1',
        x: 4,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '5-1',
        x: 5,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '6-1',
        x: 6,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      // Row 2
      {
        id: '0-2',
        x: 0,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '1-2',
        x: 1,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '2-2',
        x: 2,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '3-2',
        x: 3,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '4-2',
        x: 4,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '5-2',
        x: 5,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 8 },
      },
      {
        id: '6-2',
        x: 6,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      // Row 3
      {
        id: '0-3',
        x: 0,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '1-3',
        x: 1,
        y: 3,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '2-3',
        x: 2,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '3-3',
        x: 3,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 9 },
      },
      {
        id: '4-3',
        x: 4,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '5-3',
        x: 5,
        y: 3,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '6-3',
        x: 6,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      // Row 4
      {
        id: '0-4',
        x: 0,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '1-4',
        x: 1,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '2-4',
        x: 2,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '3-4',
        x: 3,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '4-4',
        x: 4,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '5-4',
        x: 5,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '6-4',
        x: 6,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      // Row 5
      {
        id: '0-5',
        x: 0,
        y: 5,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '1-5',
        x: 1,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 8 },
      },
      {
        id: '2-5',
        x: 2,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '3-5',
        x: 3,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '4-5',
        x: 4,
        y: 5,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '5-5',
        x: 5,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '6-5',
        x: 6,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 9 },
      },
      // Row 6
      {
        id: '0-6',
        x: 0,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '1-6',
        x: 1,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '2-6',
        x: 2,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '3-6',
        x: 3,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '4-6',
        x: 4,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '5-6',
        x: 5,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '6-6',
        x: 6,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
    ],
    goalNodes: [{ x: 4, y: 0 }],
    maxMoves: 99,
    compressionDelay: 0,
    compressionEnabled: false,
    targetScore: 0,
    timeLimit: 0,
  },
  {
    id: 203,
    name: 'Double Trouble',
    world: 1,
    gridSize: 7,
    tiles: [
      // Row 0 - flux makes 2 become 4, then 4+4=8
      {
        id: '0-0',
        x: 0,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '1-0',
        x: 1,
        y: 0,
        type: 'quantumFlux',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { effect: 'double' },
      },
      {
        id: '2-0',
        x: 2,
        y: 0,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '3-0',
        x: 3,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '4-0',
        x: 4,
        y: 0,
        type: 'target',
        connections: [],
        canRotate: false,
        isGoalNode: true,
        displayData: { targetSum: 8, isFulfilled: false },
      },
      {
        id: '5-0',
        x: 5,
        y: 0,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '6-0',
        x: 6,
        y: 0,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      // Row 1
      {
        id: '0-1',
        x: 0,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '1-1',
        x: 1,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '2-1',
        x: 2,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '3-1',
        x: 3,
        y: 1,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '4-1',
        x: 4,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '5-1',
        x: 5,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '6-1',
        x: 6,
        y: 1,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      // Row 2
      {
        id: '0-2',
        x: 0,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '1-2',
        x: 1,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '2-2',
        x: 2,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '3-2',
        x: 3,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 8 },
      },
      {
        id: '4-2',
        x: 4,
        y: 2,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '5-2',
        x: 5,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '6-2',
        x: 6,
        y: 2,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 9 },
      },
      // Row 3
      {
        id: '0-3',
        x: 0,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '1-3',
        x: 1,
        y: 3,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '2-3',
        x: 2,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '3-3',
        x: 3,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '4-3',
        x: 4,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      {
        id: '5-3',
        x: 5,
        y: 3,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '6-3',
        x: 6,
        y: 3,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      // Row 4
      {
        id: '0-4',
        x: 0,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '1-4',
        x: 1,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '2-4',
        x: 2,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '3-4',
        x: 3,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '4-4',
        x: 4,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 6 },
      },
      {
        id: '5-4',
        x: 5,
        y: 4,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 8 },
      },
      {
        id: '6-4',
        x: 6,
        y: 4,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      // Row 5
      {
        id: '0-5',
        x: 0,
        y: 5,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '1-5',
        x: 1,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
      {
        id: '2-5',
        x: 2,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 9 },
      },
      {
        id: '3-5',
        x: 3,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 4 },
      },
      {
        id: '4-5',
        x: 4,
        y: 5,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '5-5',
        x: 5,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 5 },
      },
      {
        id: '6-5',
        x: 6,
        y: 5,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 3 },
      },
      // Row 6
      {
        id: '0-6',
        x: 0,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 8 },
      },
      {
        id: '1-6',
        x: 1,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '*' },
      },
      {
        id: '2-6',
        x: 2,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 2 },
      },
      {
        id: '3-6',
        x: 3,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '+' },
      },
      {
        id: '4-6',
        x: 4,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 7 },
      },
      {
        id: '5-6',
        x: 5,
        y: 6,
        type: 'operator',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { symbol: '-' },
      },
      {
        id: '6-6',
        x: 6,
        y: 6,
        type: 'number',
        connections: [],
        canRotate: false,
        isGoalNode: false,
        displayData: { baseValue: 1 },
      },
    ],
    goalNodes: [{ x: 4, y: 0 }],
    maxMoves: 99,
    compressionDelay: 0,
    compressionEnabled: false,
    targetScore: 0,
    timeLimit: 0,
  },
];
